--AGGREGATE FUNCTION 
SELECT SUM(COST) AS SUM_OF_COST FROM PETRESCUE ; 
SELECT MAX(QUANTITY) FROM PETRESCUE;
SELECT AVG(COST) FROM PETRESCUE; 
SELECT AVG(COST/QUANTITY) FROM PETRESCUE WHERE ANIMAL ='Dog';


-- SCALAR AND STRING FUNCTION  
SELECT * FROM PETRESCUE;

SELECT LENGTH(ANIMAL) FROM PETRESCUE;
SELECT UCASE(ANIMAL) FROM PETRESCUE;
SELECT DISTINCT UCASE(ANIMAL) FROM PETRESCUE;
SELECT * FROM PETRESCUE WHERE  LCASE(ANIMAL) = 'cat';

--DATE AND TIME FUNCTIONS 
SELECT DAY(RESCUEDATE) FROM PETRESCUE WHERE ANIMAL= 'Cat';
SELECT SUM(QUANTITY) FROM PETRESCUE WHERE MONTH(RESCUEDATE)='05';
SELECT SUM(QUANTITY) FROM PETRESCUE WHERE DAY(RESCUEDATE)='14';
SELECT (RESCUEDATE + 3 DAYS ) FROM PETRESCUE;
SELECT (CURRENT DATE - RESCUEDATE) FROM PETRESCUE;