--String Patterns 
SELECT * FROM employees WHERE ADDRESS LIKE '%Elgin,IL%'; 
SELECT * FROM employees WHERE B_DATE LIKE '197%';
SELECT * FROM employees 
WHERE DEP_ID = 5 AND (SALARY BETWEEN 60000 AND 70000);

-- Sorting
SELECT * FROM employees ORDER BY DEP_ID;
SELECT * FROM employees ORDER BY DEP_ID DESC,L_NAME DESC;
SELECT D.DEP_NAME, E.* 
FROM EMPLOYEES AS E, departments AS D 
WHERE E.DEP_ID= D.DEPT_ID_DEP 
ORDER BY D.DEP_NAME,E.L_NAME DESC;  

-- Grouping 
SELECT * FROM EMPLOYEES;
SELECT DEP_ID, COUNT(*)
FROM EMPLOYEES 
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY 
FROM EMPLOYEES 
GROUP BY DEP_ID
HAVING COUNT(*)<4
ORDER BY AVG_SALARY;


