-- QUESTION 1 
SELECT COLNAME FROM SYSCAT.COLUMNS WHERE TABNAME='EMPLOYEES';
SELECT COLNAME FROM SYSCAT.COLUMNS WHERE TABNAME='JOB_HISTORY';
SELECT COLNAME FROM SYSCAT.COLUMNS WHERE TABNAME='JOBS';
SELECT COLNAME FROM SYSCAT.COLUMNS WHERE TABNAME='DEPARTMENTS';
SELECT COLNAME FROM SYSCAT.COLUMNS WHERE TABNAME='LOCATIONS';
SELECT F_NAME, START_DATE, DEPT_ID FROM EMPLOYEES 
FULL OUTER JOIN JOB_HISTORY 
ON EMPLOYEES.EMP_ID=JOB_HISTORY.EMPL_ID
WHERE DEPT_ID =5; 
--QUESTION 2 
SELECT F_NAME, START_DATE,DEPT_ID,JOB_TITLE FROM EMPLOYEES 
FULL OUTER JOIN JOB_HISTORY ON EMPLOYEES.EMP_ID=JOB_HISTORY.EMPL_ID  
FULL OUTER JOIN JOBS ON JOB_HISTORY.JOBS_ID= JOBS.JOB_IDENT
WHERE DEPT_ID ='5' ; 

--QUESTION 3
SELECT EMP_ID,L_NAME,DEPT_ID_DEP,DEP_NAME 
FROM EMPLOYEES 
LEFT OUTER JOIN DEPARTMENTS 
ON EMPLOYEES.DEP_ID =DEPARTMENTS.DEPT_ID_DEP;

--QUESTION 4 
SELECT EMP_ID,L_NAME,DEPT_ID_DEP,DEP_NAME 
FROM EMPLOYEES 
LEFT OUTER JOIN DEPARTMENTS 
ON EMPLOYEES.DEP_ID =DEPARTMENTS.DEPT_ID_DEP
WHERE YEAR(B_DATE) < 1980;

--QURESTION 5 
SELECT EMP_ID,L_NAME,DEPT_ID_DEP,DEP_NAME 
FROM EMPLOYEES 
LEFT OUTER JOIN DEPARTMENTS 
ON EMPLOYEES.DEP_ID =DEPARTMENTS.DEPT_ID_DEP AND YEAR(B_DATE) < 1980;

--QUESTION 6
SELECT F_NAME,L_NAME,DEP_NAME FROM EMPLOYEES 
FULL OUTER JOIN DEPARTMENTS 
ON EMPLOYEES.DEP_ID =DEPARTMENTS.DEPT_ID_DEP;

--QUESTION 7 
SELECT F_NAME,L_NAME,DEP_NAME,SEX FROM EMPLOYEES 
FULL OUTER JOIN DEPARTMENTS 
ON EMPLOYEES.DEP_ID =DEPARTMENTS.DEPT_ID_DEP
AND SEX = 'M';
