--SELECT * FROM EMPLOYEES WHERE SALARY < AVG(SALARY);
SELECT * FROM EMPLOYEES 
WHERE SALARY <(SELECT AVG(SALARY)FROM EMPLOYEES);
--SELECT EMP_ID, SALARY, MAX(SALARY) AS MAX_SALARY FROM EMPLOYEES;
SELECT EMP_ID, SALARY, (SELECT MAX(SALARY) FROM EMPLOYEES) AS MAX_SALARY 
FROM EMPLOYEES;

SELECT * FROM
(SELECT EMP_ID, F_NAME, L_NAME, JOB_ID,MANAGER_ID,DEP_ID FROM EMPLOYEES)
AS EMP6ALL;
